// Arc Tracker quotes, one list per archetype: Kaminari lines inspired by anime characters who fit it.
// Each row is [character it is inspired by, the line].
// A new quote drops every Monday and Thursday. Used in two places: the tracker (build.mjs copies this
// list in) and the quote notification (api/arc-push.js). Add, remove or reword rows freely.
const LINES = {
  strategist: [
    ['Shikamaru', 'The smartest move is sometimes the one nobody sees coming.'],
    ['L', 'If you understand the board, you don’t have to fear the next move.'],
    ['Shikamaru', 'You don’t win by being stronger. You win by understanding the situation.'],
    ['L', 'Every action leaves a pattern. Find the pattern, and you find the answer.'],
    ['Shikamaru', 'There’s no point rushing into a fight you haven’t already thought through.'],
    ['L', 'The person who controls the information controls the game.'],
    ['Shikamaru', 'Think before you move. Think again before you think you’re finished.'],
    ['L', 'A weakness becomes dangerous when your opponent knows you have one.'],
    ['Shikamaru', 'Sometimes the best victory is making your enemy defeat themselves.'],
    ['L', 'The obvious answer is usually the first answer you should question.'],
    ['Shikamaru', 'You don’t need a perfect plan. You need a plan for what happens when it fails.'],
    ['L', 'Observation is useless unless you’re willing to act on what you discover.'],
    ['Shikamaru', 'The strongest person in the room isn’t always the one with the most power.'],
    ['L', 'If you can predict their choice, you can control the outcome.'],
    ['Shikamaru', 'A battle can be won before anybody throws a punch.'],
    ['L', 'People reveal themselves through the decisions they make under pressure.'],
    ['Shikamaru', 'Don’t fight the problem. Figure out what created it.'],
    ['L', 'One piece of information can change the entire equation.'],
    ['Shikamaru', 'The more complicated the situation looks, the more important the fundamentals become.'],
    ['Shikamaru', 'Patience isn’t hesitation. Sometimes it’s preparation.'],
    ['L', 'If you want to understand your opponent, stop listening to what they say.'],
    ['Shikamaru', 'A clever person knows when to attack. A wise one knows when not to.'],
    ['L', 'The truth doesn’t need to be obvious to be true.'],
    ['Shikamaru', 'You can’t control everything. You can control what you do next.'],
    ['Shikamaru', 'The best strategy is the one that survives reality.'],
  ],
  'demon-grind': [
    ['Guts', 'If I have to crawl, I’ll crawl. I’m still moving forward.'],
    ['Guts', 'Pain doesn’t decide when I’m finished. I do.'],
    ['Guts', 'You can break my body without breaking my will.'],
    ['Eren', 'There’s always another step, even when you can’t see the road.'],
    ['Eren', 'I’ve lost too much to stop now.'],
    ['Guts', 'The world doesn’t owe me an easy path.'],
    ['Eren', 'If there’s something I want, I’ll keep fighting until I reach it.'],
    ['Guts', 'Some battles aren’t about winning. They’re about refusing to surrender.'],
    ['Guts', 'I’ll carry the pain if it means I can keep moving.'],
    ['Eren', 'Freedom means nothing if you’re too afraid to chase it.'],
    ['Guts', 'Every scar is proof that something tried to stop me.'],
    ['Eren', 'I don’t need the road to be easy. I need it to lead somewhere.'],
    ['Guts', 'The harder life pushes me down, the harder I push back.'],
    ['Eren', 'There are things I refuse to accept, no matter the cost.'],
    ['Guts', 'I’ve survived things that were supposed to kill me.'],
    ['Eren', 'Giving up would mean everything I suffered was for nothing.'],
    ['Guts', 'I don’t fight because I’m fearless. I fight because stopping scares me more.'],
    ['Eren', 'If destiny stands in my way, I’ll fight destiny too.'],
    ['Guts', 'My strength isn’t that I never break. It’s that I keep getting back up.'],
    ['Eren', 'There’s no going back to the person I was before all this.'],
    ['Guts', 'The world can take everything from you except the choice to keep going.'],
    ['Eren', 'I’ll endure whatever comes next.'],
    ['Guts', 'When there’s nothing left to lose, you discover how much fight you still have.'],
    ['Eren', 'I’d rather fight for something impossible than accept a life I never wanted.'],
    ['Guts', 'As long as I’m breathing, the story isn’t over.'],
  ],
  prodigy: [
    ['Rock Lee', 'Talent gets you noticed. Discipline makes you undeniable.'],
    ['Deku', 'I may not have been born gifted, but I can become exceptional.'],
    ['Rock Lee', 'Every weakness is an invitation to train harder.'],
    ['Deku', 'Potential means nothing if you’re unwilling to develop it.'],
    ['Rock Lee', 'I’ll turn every limitation into another reason to work.'],
    ['Deku', 'You don’t need to start ahead to finish ahead.'],
    ['Rock Lee', 'Hard work is how you introduce yourself to opportunity.'],
    ['Deku', 'The person I become tomorrow depends on what I practice today.'],
    ['Rock Lee', 'If I’m not naturally great, then I’ll become great deliberately.'],
    ['Deku', 'Being afraid doesn’t mean you can’t become brave.'],
    ['Rock Lee', 'Every master was once someone who couldn’t do it.'],
    ['Deku', 'I want to become someone who can protect others, so I’ll train until I can.'],
    ['Rock Lee', 'I don’t need shortcuts. I need consistency.'],
    ['Deku', 'A mistake is only wasted if you refuse to learn from it.'],
    ['Rock Lee', 'My effort is something nobody can take away from me.'],
    ['Deku', 'I’ll study my weaknesses until they become strengths.'],
    ['Rock Lee', 'You become powerful by doing difficult things repeatedly.'],
    ['Deku', 'The dream gets closer every time I refuse to quit.'],
    ['Rock Lee', 'I’ll make up for what I lack with what I’m willing to do.'],
    ['Deku', 'The future version of me is counting on what I do today.'],
    ['Rock Lee', 'Being underestimated gives me another reason to improve.'],
    ['Deku', 'Courage is taking action even when your body wants you to run.'],
    ['Rock Lee', 'I don’t need everyone to believe in me. I need to keep believing in the work.'],
    ['Deku', 'Every failure gives me information about how to become better.'],
    ['Deku', 'My potential isn’t something I wait for. It’s something I build.'],
  ],
  reborn: [
    ['Zuko', 'You are not required to remain the person your past created.'],
    ['Naruto', 'I’ve fallen before. That doesn’t mean I can’t rise differently.'],
    ['Zuko', 'My past explains me. It does not own me.'],
    ['Vegeta', 'I refuse to let the person I used to be define the person I become.'],
    ['Zuko', 'Sometimes you have to lose yourself before you discover who you really are.'],
    ['Naruto', 'I know what it feels like to be rejected. I also know what it feels like to change.'],
    ['Vegeta', 'Pride can build walls, but growth teaches you how to break them.'],
    ['Zuko', 'Redemption isn’t something someone gives you. It’s something you prove.'],
    ['Naruto', 'I’m not the same person I was yesterday.'],
    ['Vegeta', 'The strongest version of yourself may be the one you haven’t become yet.'],
    ['Zuko', 'You can spend your life chasing approval or finally decide who you want to be.'],
    ['Naruto', 'Your beginnings don’t determine your ending.'],
    ['Vegeta', 'I had to lose my old identity before I could build a better one.'],
    ['Zuko', 'Changing yourself takes more courage than defending yourself.'],
    ['Naruto', 'I’ll become someone my younger self would be proud of.'],
    ['Vegeta', 'I was once driven by pride. Now I’m driven by something greater.'],
    ['Zuko', 'Sometimes becoming better means admitting you were wrong.'],
    ['Naruto', 'You can carry your past without allowing it to control your future.'],
    ['Vegeta', 'A new life begins when you stop making excuses for the old one.'],
    ['Zuko', 'The person you become after the struggle is worth the struggle.'],
    ['Naruto', 'I don’t want to erase my past. I want to grow beyond it.'],
    ['Vegeta', 'Strength isn’t just becoming stronger. It’s becoming wiser.'],
    ['Zuko', 'You can choose your path even after walking the wrong one.'],
    ['Naruto', 'I’ll turn everything I’ve been through into something meaningful.'],
    ['Vegeta', 'Rebirth begins the moment you decide your old self is no longer enough.'],
  ],
  beacon: [
    ['All Might', 'When everyone is afraid, someone has to become the reason they feel safe.'],
    ['Whitebeard', 'A leader doesn’t stand above everyone. He stands in front when danger comes.'],
    ['All Might', 'Hope is strongest when people have a reason to believe in tomorrow.'],
    ['Whitebeard', 'If my strength can protect one more person, then I’ll use it.'],
    ['All Might', 'Sometimes a smile is a weapon against despair.'],
    ['Whitebeard', 'Family isn’t about blood. It’s about who you’re willing to protect.'],
    ['All Might', 'A true symbol gives people courage even when he is afraid.'],
    ['Whitebeard', 'The people behind you should never have to wonder if you’ll stand for them.'],
    ['All Might', 'Power means little if it gives nobody hope.'],
    ['Whitebeard', 'The greatest legacy is leaving people stronger than you found them.'],
    ['All Might', 'When others lose faith, become the reason they find it again.'],
    ['Whitebeard', 'A leader carries more than his own dreams.'],
    ['All Might', 'You don’t inspire people by telling them to be fearless. You show them how to keep going.'],
    ['Whitebeard', 'Protecting your people is worth every scar.'],
    ['All Might', 'Someone has to be the light when the world gets dark.'],
    ['Whitebeard', 'The strongest people aren’t measured by what they take, but by what they protect.'],
    ['All Might', 'Give people hope, and they’ll find strength they didn’t know they had.'],
    ['Whitebeard', 'I’ll stand between my family and whatever comes for them.'],
    ['All Might', 'A hero gives people permission to believe things can get better.'],
    ['Whitebeard', 'Your name means something when others feel safe standing beside it.'],
    ['All Might', 'Strength becomes meaningful when it belongs to something greater than yourself.'],
    ['Whitebeard', 'A captain’s greatest treasure is the people who call him family.'],
    ['All Might', 'Even when you’re tired, someone may be watching you for courage.'],
    ['Whitebeard', 'If I fall protecting them, then I’ll fall knowing what I stood for.'],
    ['All Might', 'Be the person people remember when they need a reason to believe.'],
  ],
  'social-commander': [
    ['Erwin', 'People will follow someone who can give meaning to their sacrifice.'],
    ['Lelouch', 'If you want to change the world, you must first convince people to move with you.'],
    ['Erwin', 'A leader makes people believe the impossible is worth attempting.'],
    ['Lelouch', 'The greatest weapon is knowing exactly what people are willing to fight for.'],
    ['Erwin', 'Leadership means carrying the uncertainty so others can move forward.'],
    ['Lelouch', 'A revolution begins when people believe the current world is unacceptable.'],
    ['Erwin', 'You don’t command loyalty. You earn it through conviction.'],
    ['Lelouch', 'People are moved by stories more than orders.'],
    ['Erwin', 'A commander must be willing to make decisions nobody else wants to make.'],
    ['Lelouch', 'If nobody is willing to take the first step, become that person.'],
    ['Erwin', 'A leader’s confidence can become an army’s courage.'],
    ['Lelouch', 'Control the direction of the crowd, and you control the future.'],
    ['Erwin', 'You cannot ask others to sacrifice for a future you don’t believe in.'],
    ['Lelouch', 'The world changes when someone decides they refuse to accept it.'],
    ['Erwin', 'A great leader makes ordinary people believe they are capable of extraordinary things.'],
    ['Lelouch', 'Power without purpose is nothing more than noise.'],
    ['Erwin', 'The person who sees the destination first often becomes responsible for leading others there.'],
    ['Lelouch', 'Sometimes changing the world requires becoming the villain in someone else’s story.'],
    ['Erwin', 'A commander must understand the hearts of the people he leads.'],
    ['Lelouch', 'If you want loyalty, give people something worth believing in.'],
    ['Erwin', 'Fear can move people once. Purpose can move them forever.'],
    ['Lelouch', 'The future belongs to those willing to challenge the present.'],
    ['Erwin', 'A leader doesn’t eliminate fear. He gives fear a direction.'],
    ['Lelouch', 'One person with conviction can change the decisions of thousands.'],
    ['Lelouch', 'If the world refuses to change, find the people willing to change it.'],
  ],
  believer: [
    ['Luffy', 'I believe in my friends even when they stop believing in themselves.'],
    ['Tanjiro', 'Kindness is not weakness. It’s strength you choose to give.'],
    ['Luffy', 'If I believe I can reach it, I’ll keep moving toward it.'],
    ['Tanjiro', 'You can be hurt and still choose to care.'],
    ['Luffy', 'I don’t need everyone to understand my dream.'],
    ['Tanjiro', 'There is always something worth protecting.'],
    ['Luffy', 'I trust the people beside me because they’ve given me reasons to.'],
    ['Tanjiro', 'Even in darkness, I will search for a way forward.'],
    ['Luffy', 'If my friends are counting on me, quitting isn’t an option.'],
    ['Tanjiro', 'A person’s heart can remain kind even after suffering.'],
    ['Luffy', 'I’d rather chase an impossible dream than live without one.'],
    ['Tanjiro', 'You don’t need to become cruel just because the world has been cruel to you.'],
    ['Luffy', 'I know my dream sounds crazy. That’s never stopped me.'],
    ['Tanjiro', 'Protecting someone can give you strength you never knew you had.'],
    ['Gon', 'I believe there’s always a way if we keep looking.'],
    ['Tanjiro', 'The people you love can become the reason you discover your strength.'],
    ['Luffy', 'I don’t care how impossible it looks. I’m still going.'],
    ['Tanjiro', 'Hope begins when you refuse to let despair make your decisions.'],
    ['Luffy', 'My friends are part of my dream.'],
    ['Tanjiro', 'Sometimes believing in someone is the greatest gift you can give them.'],
    ['Gon', 'I’ll keep reaching for what I want until I find out how far I can go.'],
    ['Luffy', 'The future is worth believing in because we can still shape it.'],
    ['Tanjiro', 'Even after losing something precious, you can still choose to move forward.'],
    ['Luffy', 'I trust my heart, and I trust the people walking beside me.'],
    ['Gon', 'Believe in what matters to you, even when nobody else understands.'],
  ],
  underdog: [
    ['Krillin', 'Being weaker doesn’t mean you stop showing up.'],
    ['Yuji', 'I don’t have to be the strongest to stand my ground.'],
    ['Krillin', 'Sometimes courage is all you have, so you learn to use it.'],
    ['Yuji', 'I may be scared, but there are things I still have to do.'],
    ['Krillin', 'The gap between you and the strongest doesn’t matter if you refuse to quit.'],
    ['Yuji', 'I’ll keep moving even when I don’t know if I can win.'],
    ['Krillin', 'You learn who you really are when you fight from behind.'],
    ['Yuji', 'Being afraid doesn’t make me weak. Letting fear decide for me would.'],
    ['Krillin', 'I know I’m outmatched. I’m fighting anyway.'],
    ['Yuji', 'Sometimes all you can do is take the next step.'],
    ['Krillin', 'Nobody gets to decide my limits for me.'],
    ['Yuji', 'I don’t need to be special to make my life matter.'],
    ['Krillin', 'The underdog’s advantage is knowing what it means to struggle.'],
    ['Yuji', 'If I can help someone, then I have a reason to keep fighting.'],
    ['Krillin', 'I started behind. That doesn’t mean I have to stay there.'],
    ['Yuji', 'Strength isn’t always about winning. Sometimes it’s refusing to run.'],
    ['Krillin', 'Every time I survive something stronger than me, I become stronger too.'],
    ['Yuji', 'I’m scared of losing people, but that’s exactly why I have to fight.'],
    ['Krillin', 'You don’t need overwhelming power to make an impact.'],
    ['Yuji', 'Even an ordinary person can choose to do something extraordinary.'],
    ['Krillin', 'I may never be the strongest, but I can still be dependable.'],
    ['Yuji', 'The fact that I’m struggling doesn’t mean I’m failing.'],
    ['Krillin', 'Sometimes the hardest victory is convincing yourself not to give up.'],
    ['Yuji', 'I’ll fight with whatever I have because someone has to.'],
    ['Krillin', 'You don’t become an underdog by losing. You become one by starting without the advantages.'],
  ],
  'free-spirit': [
    ['Gintoki', 'I’ll live my life my way, even if my way makes no sense to anyone else.'],
    ['Bon Clay', 'Freedom means being yourself without asking permission.'],
    ['Gintoki', 'Life is too short to spend it pretending to be someone else.'],
    ['Bon Clay', 'A true friend doesn’t abandon you when the world tells them to.'],
    ['Gintoki', 'I don’t need a perfect life. I just want one that belongs to me.'],
    ['Bon Clay', 'Be proud of who you are, even when nobody understands you.'],
    ['Gintoki', 'Rules are useful until they start telling you who you’re allowed to be.'],
    ['Bon Clay', 'The greatest freedom is loving people without being ashamed of it.'],
    ['Gintoki', 'I’d rather be ridiculous and honest than respectable and fake.'],
    ['Bon Clay', 'You can choose your own family.'],
    ['Gintoki', 'There’s nothing wrong with taking the long way if it’s your road.'],
    ['Bon Clay', 'Never abandon your identity just because someone else doesn’t approve of it.'],
    ['Gintoki', 'A boring life is the one you live according to somebody else’s expectations.'],
    ['Bon Clay', 'True friendship means standing beside someone when standing beside them costs you something.'],
    ['Gintoki', 'I don’t want to become someone important. I want to remain myself.'],
    ['Bon Clay', 'You don’t need permission to love, laugh, or be yourself.'],
    ['Gintoki', 'Sometimes the best way to survive life is to stop taking it so seriously.'],
    ['Bon Clay', 'Your spirit belongs to you. Don’t hand it over to anyone.'],
    ['Gintoki', 'I’ll take freedom over status every time.'],
    ['Bon Clay', 'A person’s true beauty is being unapologetically themselves.'],
    ['Gintoki', 'I don’t need the world to make sense for me to enjoy being alive.'],
    ['Bon Clay', 'If I call you my friend, I’ll prove it when it matters.'],
    ['Gintoki', 'The best adventures usually start when you stop following the plan.'],
    ['Bon Clay', 'Never let shame convince you to hide the person you are.'],
    ['Gintoki', 'Live honestly enough that nobody else gets to write your story.'],
  ],
  'balanced-master': [
    ['Uncle Iroh', 'Make the tea slowly. Do the work the same way.'],
    ['Kakashi', 'You know every technique. The one that counts is showing up.'],
    ['Uncle Iroh', 'Balance is not standing still. It is small corrections, every day.'],
    ['Kakashi', 'Look after your team, and remember you are on it.'],
    ['Uncle Iroh', 'Be proud of your light and honest about your shadow. Both walked you here.'],
  ],
};

export const QUOTES = Object.fromEntries(Object.entries(LINES).map(([key, rows]) => [key, rows.map(([c, q]) => ({ c, q }))]));

// Quotes drop twice a week. For a calendar date ("YYYY-MM-DD") this gives which drop is current
// (a running count of Mondays and Thursdays) and whether that date is itself a drop day.
export function dropFor(dateStr) {
  const [y, m, d] = String(dateStr).split('-').map(Number);
  const sinceMonday = Math.floor(Date.UTC(y, (m || 1) - 1, d || 1) / 86400000) - 4; // 5 Jan 1970 was a Monday
  const week = Math.floor(sinceMonday / 7), dow = sinceMonday - week * 7; // dow: 0 = Monday ... 6 = Sunday
  return { index: week * 2 + (dow >= 3 ? 1 : 0), isDropDay: dow === 0 || dow === 3 };
}

// The current quote for an archetype on a date. It changes each Monday and Thursday, so the tracker
// and the notification always agree.
export function quoteFor(archetypeKey, dateStr) {
  const list = QUOTES[archetypeKey];
  if (!list || !list.length) return null;
  const { index } = dropFor(dateStr);
  return list[((index % list.length) + list.length) % list.length];
}
